site_name: Zest
pages:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Routing: routing.md
    - Controllers: controller.md
    - Views: views.md
    - Integrating twig with Zest: integrating-twig-with-Zest.md
    - Models: model.md
    - Validation: validation.md
    - Sending Mail: mail.md
    - Database Manipulation: database.md
    - Session Handling: session.md
    - Cryptography: cryptography.md
    - Site Maintenance: maintenance.md
    - Zest Console: console.md
    - Upgrade to 1.9.1: UPGRADE-1.9.1.md
    - Upgrade to 1.9.3: Upgrade to 1.9.3.md
    - Upgrade to 1.9.4: UPGRADE-1.9.4.md
    - Upgrade to 2.0.1: UPGRADE-2.0.1.md
    - Contribute: zestcontribute.md
theme: readthedocs    
    

